### ISSUE TITLE
Gulp Task

### ISSUE THREAD

**Issue by zeeshanjan82** [sequelize/gulp-sequelize#1]
Where can I find this gulp task and what does this task do?

**Comment by mickhansen** [comment]
It doesn't exist, evident from the very empty repository ;p

**Comment by jalcine** [comment]
[**@mickhansen**](https://github.com/mickhansen) commented on [Jul 12, 2015, 5:00 AM EDT](https://github.com/sequelize/gulp-sequelize/issues/1#issuecomment-120702443):

> It doesn't exist, evident from the very empty repository ;p

Is this a place holder for an official one in the future?

**Comment by sdepold** [comment]
It's more like someone wanted to extract the logic from the CLI to this module and never started doing so.

**Comment by jalcine** [comment]
[**@sdepold**](https://github.com/sdepold) commented on [Aug 25, 2015, 1:21 AM EDT](https://github.com/sequelize/gulp-sequelize/issues/1#issuecomment-134479374):

> It's more like someone wanted to extract the logic from the CLI to this module and never started doing so.

D'oh! That'd be awesome to have. Could this be hooked up with a Bountysource kind of thing? That'd compel me to look into this (time being tight and all).

**Comment by treythomas123** [comment]
I agree -- something like this would be nice to have. I didn't see an easy JS interface into sequelize-cli, so my gulp tasks for migrations currently just make shell calls to `./node_modules/sequelize-cli/bin/sequelize` with gulp-shell.

I'd prefer something like:

``` js
gulp.task('migrate', function() {
    return sequelize.migrate();
});
```

Not sure if this would be better to put into [sequelize/sequelize](https://github.com/sequelize/sequelize) or a separate package like gulp-sequelize.

**Comment by janmeier** [comment]
Umzug has an api for programmatic usage https://github.com/sequelize/umzug#usage

**Comment by sdepold** [comment]
Bountysource: https://www.bountysource.com/issues/24171279-gulp-task

**Comment by treythomas123** [comment]
@zeeshanjan82 @jalcine I added some initial functionality for this if you want to try it out.

Closing this issue -- feel free to write another one if you have other features you'd like to see added
